// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_0dspCiGiiRAuHXhAPio56gGIkkqOgrY',
    appId: '1:582711573400:web:d1e35896ded2d15bee09ed',
    messagingSenderId: '582711573400',
    projectId: 'kyty-marco-martinez',
    authDomain: 'kyty-marco-martinez.firebaseapp.com',
    storageBucket: 'kyty-marco-martinez.appspot.com',
    measurementId: 'G-JFXEMJ58EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUpGtgIh9XaQCFjfbkwB38apFZiGOy7z4',
    appId: '1:582711573400:android:2f622b00ae9f90e0ee09ed',
    messagingSenderId: '582711573400',
    projectId: 'kyty-marco-martinez',
    storageBucket: 'kyty-marco-martinez.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7RvguynzmRW1Hsug-yxqS_JaAIXshrP8',
    appId: '1:582711573400:ios:9ab37506ae014676ee09ed',
    messagingSenderId: '582711573400',
    projectId: 'kyty-marco-martinez',
    storageBucket: 'kyty-marco-martinez.appspot.com',
    iosBundleId: 'org.marcomartinez.kyty',
  );
}
